# Generated by Django 5.2.7 on 2025-10-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_ghl_id', models.CharField(help_text='ID de GHL de la cita', max_length=100, unique=True)),
                ('contact_id', models.CharField(help_text='ID del Contacto en GHL', max_length=100)),
                ('preference_id', models.CharField(blank=True, help_text='ID de la Preferencia de MP', max_length=100, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, help_text='ID del Pago real en MP (para idempotencia)', max_length=100, null=True, unique=True)),
                ('init_point', models.URLField(blank=True, help_text='URL de Checkout Pro', max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencia de Pago MP',
                'verbose_name_plural': 'Preferencias de Pago MP',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
